const fortuneMessagesEn = [
  "Your future is bright.",
  "Good things are coming your way.",
  "You are going to achieve your goals.",
  "Happiness is in your future.",
  "Let calm be your guide in turbulent times.",
  "Wisdom is acquired with time and experience.",
  "Small acts of kindness can have a lasting impact.",
  "Every cloud has a silver lining.",
  "Sow positive thoughts and you will reap a fulfilling life.",
  "Sometimes, the best path is the one you least expect.",
  "Patience is the key to overcoming challenges.",
  "Success comes to those who persevere.",
  "Do your best and let the universe take care of the rest.",
  "There's no long road with a good traveling companion.",
  "Learn from your mistakes and move forward with determination.",
  "Gratitude transforms what we have into enough.",
  "Trust your intuition; it often knows more than you think.",
  "Storms don't last forever; calm always comes.",
  "You can't change the wind, but you can adjust the sails.",
  "Happiness is not a destination, it's a journey.",
  "Love is the universal language we all can understand.",
  "Live with passion and purpose, and you'll find your way.",
  "Sometimes, the best answer is silence.",
  "True greatness comes from serving others.",
  "The best lessons are learned from mistakes.",
  "Authenticity is the master key to human connection.",
  "Blessings come in forms we often don't expect.",
  "True beauty lies in the heart and soul.",
  "Gratitude is the attitude that transforms lives.",
  "Strength doesn't come from winning. Your struggles build your strengths.",
  "Life is a journey, not a destination.",
  "Love is the answer, no matter what the question.",
  "Happiness is a choice you make every day.",
  "Small actions can have a big impact.",
  "Patience is the strength of the soul.",
  "True wealth comes from inner satisfaction.",
  "The best way to predict the future is to create it.",
  "Friendship is a treasure to be cherished.",
  "Accept others as they are, without judgment or prejudice.",
  "Humility is the path to wisdom.",
  "Hope is the light that guides in darkness.",
  "Peace begins with a smile.",
  "Forgiveness is the greatest gift you can give yourself.",
  "Life is a blank canvas; you choose the colors.",
  "Change is inevitable; growth is optional.",
  "Love knows no bounds; it is infinite and eternal.",
  "Courage is not the absence of fear, but the ability to move forward despite it.",
  "Serenity comes from accepting the things you cannot change.",
  "Resilience is the ability to rise again and again after adversity.",
  "Gratitude transforms ordinary moments into extraordinary blessings.",
  "Truth may be painful, but it's always liberating.",
  "Beauty is not in what you see, but in how you see things.",
  "Faith moves mountains and sustains the soul.",
  "Life is a gift; every day is a blessing.",
  "Joy is found in the small moments of everyday life.",
  "Generosity is the key to unlocking others' hearts.",
  "Kindness is contagious; spread it whenever you can.",
  "Perseverance is the key to success.",
  "Happiness is not found in what we possess, but in who we are.",
  "Empathy is the bridge that connects people.",
  "Inspiration comes from everywhere; keep your eyes and heart open.",
  "Compassion is the noblest expression of humanity.",
  "Life is a journey of self-discovery; enjoy the ride.",
  "Patience is a virtue that brings great rewards.",
  "Gratitude is the best antidote against negativity.",
  "True greatness lies in selfless service to others.",
  "True friendship is an invaluable treasure.",
  "Simplicity is the ultimate sophistication.",
  "Creativity is the driving force of human progress.",
  "Curiosity is the engine of learning and innovation.",
  "Kindness is the language the deaf can hear and the blind can see.",
  "Trust is the foundation of all solid relationships.",
  "Flexibility is the key to adapting to change.",
  "Perseverance is the mother of success.",
  "Freedom begins with the courage to be yourself.",
  "Wisdom is acquired by recognizing that you still have much to learn.",
  "Harmony is the balance between body, mind, and spirit.",
  "Determination is the force that takes you from where you are to where you want to be.",
  "Hope is the beacon that guides in darkness.",
  "Authenticity is the essence of true beauty.",
  "Humility is the foundation of all virtues.",
  "Integrity is doing the right thing even when no one is watching.",
  "Gratitude is the seed of happiness.",
  "Inner peace is the refuge in times of storm.",
  "Every investment you make is a seed planted for your financial future. Invest wisely!",
  "Financial success is a journey, not a destination. Enjoy the journey and celebrate every achievement along the way.",
  "Don't underestimate the power of your ideas. They can become your source of wealth.",
  "Abundance is your birthright. Claim your part!",
  "Prosperity awaits you on the other side of fear. Overcome it and move towards abundance.",
  "Fortune favors those willing to take calculated risks. Be bold in your financial decisions!",
  "The key to attracting wealth is believing in your ability to create it. Believe in yourself and your potential for financial success.",
  "Every dollar you earn is one step closer to financial independence. Value every cent and use it wisely!",
  "Wealth is the result of making smart and consistent financial decisions. Take control of your finances and direct your destiny!",
  "Money is a tool that allows you to live the life you desire. Use it with purpose and generosity.",
  "Wealth begins in the mind. Cultivate an abundance mindset and you will attract prosperity in all areas of your life.",
  "Every financial challenge is an opportunity to learn and grow. Maintain a positive attitude and seek creative solutions.",
  "Prosperity is the result of making decisions aligned with your values and goals. Keep focused on what really matters.",
  "Abundance is a state of mind. Cultivate an attitude of gratitude and appreciation for all you have, and you'll attract more good things into your life.",
  "Money is an energy that flows to those in tune with prosperity. Align your thoughts, emotions, and actions with abundance, and you'll attract wealth into your life.",
  "Every investment you make is a seed planted for your financial future. Choose wisely where and how to plant those seeds, and you'll reap the rewards of prosperity.",
  "Wealth is not measured by the amount of money you have in the bank, but by the quality of life you can enjoy. Seek true wealth in experiences, relationships, and happy moments.",
  "Money is a renewable resource. No matter how much you spend, there will always be more opportunities to earn and multiply your wealth.",
  "Trust in your ability to attract abundance into your life.",
  "Prosperity is not just having a lot of money but feeling fulfilled and satisfied with what you have.",
  "Cultivate an attitude of gratitude for the blessings you already have, and you'll attract more good things into your life.",
  "Abundance is your birthright. Don't be afraid to claim it and live a life of prosperity and fulfillment.",
  "Trust the universe and yourself to manifest your financial dreams into reality.",
  "In the mystery of love, you will find the answers you seek.",
  "The universe whispers love secrets with every heartbeat.",
  "In the maze of love, your destiny awaits to be discovered.",
  "The stars conspire in your favor to reveal the path to true love.",
  "In the pages of destiny, you will find the story of your love.",
  "Let fortune guide you to the love you deserve.",
  "In the reflection of your dreams, you'll find the key to unlock true love.",
  "The wind carries love messages waiting to be deciphered in every whisper.",
  "The love oracle invites you to uncover the mysteries fate has in store for you.",
  "Every rose holds a love secret waiting to be unveiled.",
  "In the corners of time, you will find the answers to your love desires.",
  "The whispers of destiny will guide you to the love you've been searching for.",
  "In the folds of the universe, you'll find clues to your love destiny.",
  "Let the stars illuminate your path to eternal love.",
  "In the mirror of the soul, you'll find the image of your true love.",
  "Every encounter is a sign from destiny bringing you closer to your true love.",
  "The universe's signals lead you to a deeper and truer love.",
  "Let fortune unveil the secrets of your heart and guide you to eternal love.",
  "The universe reveals hidden clues leading you to a more authentic love.",
  "In the echo of the wind, you'll hear the words of love destiny has in store for you.",
  "Tune into the energy of love and discover the messages the universe has for you.",
  "The path to true love is marked by the stars shining in the night sky.",
  "In the whispers of the universe, you'll find the answers to your love desires.",
  "Every step you take brings you closer to the love destiny has in store for you.",
  "In the language of the stars, you will find the words of love that destiny has written for you.",
  "Let fortune guide you to the love that awaits you on the horizon.",
  "In the book of destiny, you will find the pages that narrate your love story.",
  "The mystery of love awaits you at every corner of the universe, ready to be discovered.",
  "Let the signs of the universe lead you to the love that awaits you.",
  "In the dreams of the heart, you will find the answers to your love desires.",
  "Destiny whispers words of love to you, waiting to be heard in the silence of the night.",
  "Each star in the sky is a glimmer of hope guiding you towards eternal love.",
  "In the dance of destiny, you will find the partner that complements your soul.",
  "The signs of the universe lead you to a deeper and more meaningful love.",
  "Let fortune show you the way to love that transcends the barriers of time and space.",
  "In the mystery of love, you will find the key that will unlock the doors of your heart.",
  "Each encounter is an opportunity to discover the love that destiny has prepared for you.",
  "In the stars that shine in the sky, you will find the guidance that will lead you to eternal love.",
  "Let the magic of the universe take you to the love you have always sought.",
  "In the whisper of the wind, you will hear the promises of love that destiny has reserved for you.",
  "Destiny takes you by the hand towards a love that transcends time and space.",
  "On the horizon of love, you will find the answers you have been seeking.",
  "The signs of the universe show you the way to a love that will change your life forever.",
  "In the mirror of the soul, you will find the image of your true love reflected.",
  "In the fabric of destiny, you will find the threads that connect your heart to true love.",
  "Let the stars guide your steps towards a love that will light up your life.",
  "In the deepest corner of your heart, you will find the love you have been searching for.",
  "The universe conspires in your favor to lead you to the love that awaits you.",
  "Let fortune show you the way to a love that transcends the barriers of time and space.",
  "Let calm be your guide in turbulent times.",
  "Wisdom is gained with time and experience.",
  "Small acts of kindness can have a lasting impact.",
  "There is no evil that does not come with some good.",
  "Sow positive thoughts and you will reap a fulfilling life.",
  "Sometimes, the best path is the one you least expect.",
  "Patience is the key to overcoming challenges.",
  "Success comes to those who persevere.",
  "Do your best and let the universe take care of the rest.",
  "There is no long road when you have a good traveling companion.",
  "Learn from your mistakes and move forward with determination.",
  "Gratitude transforms what we have into enough.",
  "Trust your intuition; it often knows more than you think.",
  "Storms do not last forever; calm always comes.",
  "You cannot change the wind, but you can adjust the sails.",
  "Happiness is not a destination, it is a journey.",
  "Love is the universal language that we can all understand.",
  "Live with passion and purpose, and you will find your way.",
  "Sometimes, the best answer is silence.",
  "True greatness comes from serving others.",
  "The best lessons are learned from mistakes.",
  "Authenticity is the master key to human connection.",
  "Blessings come in forms we often do not expect.",
  "True beauty lies in the heart and soul.",
  "Gratitude is the attitude that transforms lives.",
  "Strength does not come from winning. Your struggles develop your strengths.",
  "Life is a journey, not a destination.",
  "Love is the answer, no matter what the question.",
  "Happiness is a choice you make every day.",
  "Small actions can have a big impact.",
  "Patience is the strength of the soul.",
  "True wealth comes from inner satisfaction.",
  "The best way to predict the future is to create it.",
  "Friendship is a treasure that should be cherished.",
  "Accept others as they are, without judgment or prejudice.",
  "Humility is the path to wisdom.",
  "Hope is the light that guides in darkness.",
  "Peace begins with a smile.",
  "Forgiveness is the greatest gift you can give yourself.",
  "Life is a blank canvas; you choose the colors.",
  "Change is inevitable; growth is optional.",
  "Love knows no bounds; it is infinite and eternal.",
  "Courage is not the absence of fear, but the ability to move forward despite it.",
  "Serenity comes from accepting the things you cannot change.",
  "Resilience is the ability to rise again and again after adversity.",
  "Gratitude transforms ordinary moments into extraordinary blessings.",
  "The truth may be painful, but it is always liberating.",
  "Beauty is not in what you see, but in how you see things.",
  "Faith moves mountains and sustains the soul.",
  "Life is a gift; every day is a blessing.",
  "Joy is found in the small moments of everyday life.",
  "Generosity is the key to opening others' hearts.",
  "Kindness is contagious; spread it whenever you can.",
  "Perseverance is the key to success.",
  "Happiness is not found in what we possess, but in who we are.",
  "Empathy is the bridge that connects people.",
  "Inspiration comes from everywhere; keep your eyes and heart open.",
  "Compassion is the noblest expression of humanity.",
  "Life is a journey of self-discovery; enjoy the ride.",
  "Patience is a virtue that brings great rewards.",
  "Gratitude is the best antidote to negativity.",
  "True greatness lies in selfless service to others.",
  "True friendship is an invaluable treasure.",
  "Simplicity is the ultimate sophistication.",
  
  "Understanding is the key to resolving conflicts.",
  "Acceptance is the first step towards inner peace.",
  "Patience is the calm in the midst of the storm.",
  "Courage is facing your fears and moving forward.",
  "Compassion is the willingness to alleviate the suffering of others.",
  "Wisdom is the ability to discern what is true, what is right, what is meaningful.",
  "Kindness is the universal currency of humanity.",
  "Humility is the mark of a true leader.",
  "Generosity is giving more than is expected, without expecting anything in return.",
  "It's time to shine!",
  "Dare to be extraordinary.",
  "Success awaits those who dare to act.",
  "Your destiny is in your hands.",
  "Fortune favors the bold.",
  "Take the first step towards your dreams.",
  "Don't wait for the perfect moment, make it perfect.",
  "Act with courage and determination.",
  "Today is the day to start something new.",
  "Embrace the adventure that awaits you.",
  "Make every day count.",
  "The future belongs to those who rise early to pursue their dreams.",
  "Don't wait for opportunities to come, create them.",
  "Turn your dreams into reality with every action.",
  "Pursue your goals with passion and determination.",
  "Break the barriers that hold you back.",
  "Don't put off until tomorrow what you can do today.",
  "Make every moment count.",
  "Success is the result of constant action.",
  "The first step towards success is deciding to try.",
  "Act with confidence and conviction.",
  "Don't fear failure, fear not trying.",
  "The world is full of possibilities waiting to be discovered.",
  "If you want something, go for it with all your heart.",
  "Never underestimate the power of your actions.",
  "Don't let fear stop you, act despite it.",
  "Life is an adventure, live it to the fullest!",
  "Take control of your destiny.",
  "Every action you take brings you one step closer to your dreams.",
  "Act as if success is guaranteed.",
  "Do what you love and success will follow.",
  "Don't wait for opportunities to knock on your door, go out and find them.",
  "Fortune smiles upon those who strive.",
  "Dare to do what others fear.",
  "Keep moving forward even when it seems impossible.",
  "Life is an adventure waiting to be lived.",
  "Action is the key to progress.",
  "Don't settle for the ordinary, aspire to the extraordinary.",
  "Every step you take brings you closer to your goals.",
  "Act as if each day is the most important.",
  "Fortune favors those who strive for it.",
  "Never underestimate the power of determined action.",
  "Don't let fear hold you back from pursuing your dreams.",
  "Turn your dreams into goals and your goals into reality.",
  "Life rewards those who dare to act.",
  "Make your dreams bigger than your fears.",
  "Don't wait for conditions to be perfect, make them perfect with your action.",
  "Luck favors those who are willing to work hard.",
  "Dare to pursue the impossible.",
  "Act now, tomorrow may be too late.",
  "True love is the greatest fortune you can find.",
  "Love awaits you at every corner, you just need to be ready to receive it.",
  "Fortune smiles upon hearts that are open to love.",
  "In the game of love, luck favors the brave.",
  "Love is the most precious treasure you can find.",
  "Every broken heart is an opportunity to find a truer love.",
  "True fortune is finding someone who shares your madness.",
  "Love comes when you least expect it, but always at the perfect time.",
  "In love, as in fortune, sometimes you need to take risks to win.",
  "Every challenge in love is an opportunity to grow and strengthen the relationship.",
  "Love is the true wealth of life.",
  "Luck in love is finding someone who loves you even on your worst days.",
  "Love is the magic that turns the ordinary into extraordinary.",
  "True fortune is waking up every day beside someone who loves you.",
  "Love is the bridge that unites two hearts in one melody.",
  "Luck in love is finding someone who accepts you just as you are.",
  "True love is the greatest blessing you can receive.",
  "In love, as in life, luck favors those who dare to love.",
  "Love is a journey, and fortune is finding someone who walks by your side.",
  "Luck in love is finding someone who makes you feel at home wherever you are.",
  "True love is the greatest adventure you can embark on.",
  "In love, as in fortune, sometimes you need to take risks to find the true reward.",
  "Luck in love is finding someone who makes you smile even on the darkest days.",
  "Love is the most valuable currency you can possess.",
  "True fortune is sharing your life with someone who makes you feel complete.",
  "Love is the force that moves the world and the fortune that gives meaning to life.",
  "Luck in love is finding someone who makes you feel alive.",
  "Love is the greatest gift you can give and receive.",
  "Fortune in love is finding someone who makes you feel loved every day.",
  "Love is the greatest blessing you can receive.",
  "Luck in love is finding someone who makes you feel at home in their heart.",
  "Love is the magic that turns the ordinary into extraordinary.",
  "True fortune is sharing your life with someone who makes you feel at home wherever you are.",
  "Love is the most precious treasure you can find in life.",
];
